### ISSUE TITLE
ModuleNotFoundError: No module named 'Utils'

### ISSUE THREAD

**Issue by Acer888** [HKUDS/RGA#1]
I'd like to express my appreciation for the work you've done on this project. 

However, I encountered the following problem while running it: 
`ModuleNotFoundError: No module named 'Utils'`

Any guidance on resolving this would be greatly appreciated. Thank you very much for your time and assistance. I eagerly await your response.

**Comment by wxy015513** [comment]
Can you provide the requirements.txt file?

**Comment by Acer888** [comment]
> Can you provide the requirements.txt file?

you can try this:

[requirement.txt](https://github.com/HKUDS/GraphAug/files/14845457/requirement.txt)

**Comment by lizzyhku** [comment]
> I'd like to express my appreciation for the work you've done on this project.
> 
> However, I encountered the following problem while running it: `ModuleNotFoundError: No module named 'Utils'`
> 
> Any guidance on resolving this would be greatly appreciated. Thank you very much for your time and assistance. I eagerly await your response.

I am sorry for my late reply. I have uploaded Utils files. Thanks.

**Comment by Acer888** [comment]
Thank you, the issue has been resolved.

**Comment by lizzyhku** [comment]
You are welcome.
